version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: conduit_postgres
    environment:
      POSTGRES_USER: conduit_test_user
      POSTGRES_PASSWORD: conduit!
      POSTGRES_DB: conduit_test_db
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
